var DIRECTORY_CLASS = "directory";
var SUBDIRECTORY_CLASS = "subdirectory";
var INCLUDES_DIRECTORY_ID = "jams-dogpit";
var JAM_INFO_ID = "jam-info";
var PRETTYPRINT_CLASS = "prettyprint";
var LINENUMS_CLASS = "linenums";
var JAMS_TABLE = "Jams";
var RESULTS_TABLE = "Results";
var GAMES_TABLE = "Games"
var DEFINITIONS_TABLE = "Definitions";
var DIRECTORIES_TABLE = "Directories";
var SMALL_ACCENT = `<div class="accent-small"></div>`;
var JAM_NAME = 1;
var JAM_ORGANIZER = 3;
var JAM_THEME = 4;
var JAM_URL = 5;
var JAM_PAGE = 6;
var GAME_TITLE = 1;
var GAME_USER = 2;
var GAME_URL = 3;
var GAME_TEAM = 4;
var GAME_SCORE = 7;
var TITLE = "The Dogpitjamcronomicon"
var BASE = "/"
var SCRIPTS_PATH = BASE + "Scripts/";
var STYLE_PATH = BASE + "Styles/Style.css";
var STYLE_ID = "MainStyle";
var LIBRARY_PATH = BASE + "Library/";
var SQL_SCRIPT_ID = "SQLScript";
var SQL_SCRIPT = "sql-wasm.js";
var SQL_PATH = "https://kripken.github.io/sql.js/dist/";
var DB_PATH = "https://dogpitjams.com/Data/Jams.db";